export default function Terms({ onBack }) {
  return (
    <div className="mx-auto max-w-2xl space-y-6 px-4 py-8">
      <button onClick={onBack} className="btn-ghost text-sm">← Back</button>

      <div className="card p-6 space-y-5">
        <div>
          <h1 className="font-display text-2xl font-bold">Terms of Service</h1>
          <p className="mt-1 text-sm text-slate2">Last updated: September 2026 · GCSEasy (gcseasy.org)</p>
        </div>

        <section className="space-y-2">
          <h2 className="font-semibold">1. The service</h2>
          <p className="text-sm text-slate2 leading-relaxed">
            GCSEasy (operated by DentEdTech) provides an AI-powered GCSE and KS3 revision platform
            at gcseasy.org. By creating an account, you agree to these terms.
          </p>
        </section>

        <section className="space-y-2">
          <h2 className="font-semibold">2. Free and Pro plans</h2>
          <ul className="text-sm text-slate2 leading-relaxed space-y-1 list-disc list-inside">
            <li><strong>Free:</strong> 5 AI questions and 5 AI tutor messages per day, resets at midnight (GMT)</li>
            <li><strong>Pro (£3.99/month or £29.99/year):</strong> 30 AI questions and 30 tutor messages per day</li>
            <li>Daily limits exist to manage AI costs and ensure fair access for all users</li>
            <li>Limits may be adjusted with reasonable notice</li>
          </ul>
        </section>

        <section className="space-y-2">
          <h2 className="font-semibold">3. Payments and cancellation</h2>
          <ul className="text-sm text-slate2 leading-relaxed space-y-1 list-disc list-inside">
            <li>Pro subscriptions are billed monthly or annually via Lemon Squeezy</li>
            <li>You may cancel at any time — access continues until the end of the billing period</li>
            <li>Refunds are handled at our discretion; contact support@gcseasy.org within 7 days of a charge if you have concerns</li>
            <li>Prices include UK VAT where applicable</li>
          </ul>
        </section>

        <section className="space-y-2">
          <h2 className="font-semibold">4. Acceptable use</h2>
          <p className="text-sm text-slate2 leading-relaxed">
            GCSEasy is for personal, non-commercial revision. You must not share accounts,
            attempt to circumvent usage limits, scrape content, or use the platform in any way
            that could harm other users or the service.
          </p>
        </section>

        <section className="space-y-2">
          <h2 className="font-semibold">5. AI-generated content</h2>
          <p className="text-sm text-slate2 leading-relaxed">
            Questions, marking and tutor responses are generated by AI and are for revision
            practice only. They may occasionally contain errors. GCSEasy is not a substitute
            for your school, teacher, or official revision materials. Always cross-check important
            information with your exam board's specification.
          </p>
        </section>

        <section className="space-y-2">
          <h2 className="font-semibold">6. Limitation of liability</h2>
          <p className="text-sm text-slate2 leading-relaxed">
            GCSEasy is provided "as is". We are not liable for exam results, errors in
            AI-generated content, or service interruptions. Our total liability is limited to
            the amount you paid in the 3 months prior to any claim.
          </p>
        </section>

        <section className="space-y-2">
          <h2 className="font-semibold">7. Changes to these terms</h2>
          <p className="text-sm text-slate2 leading-relaxed">
            We may update these terms. Continued use of GCSEasy after changes constitutes
            acceptance. Significant changes will be communicated by email.
          </p>
        </section>

        <section className="space-y-2">
          <h2 className="font-semibold">8. Governing law</h2>
          <p className="text-sm text-slate2 leading-relaxed">
            These terms are governed by the laws of England and Wales.
          </p>
        </section>

        <section className="space-y-2">
          <h2 className="font-semibold">9. Contact</h2>
          <p className="text-sm text-slate2 leading-relaxed">
            Questions? Email <a href="mailto:support@gcseasy.org" className="text-accent underline">support@gcseasy.org</a>.
          </p>
        </section>
      </div>
    </div>
  );
}
